# -*- coding: utf-8 -*-
"""data_simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ife77mGG0CVrsUKa8l-jxyw7FtInUIdQ

Following 3 cells were used for saving simulated data of different sample sizes = 100, 500, 1000 to Google Drive. After that, these csv files were added to the github.
"""

import numpy as np
import pandas as pd

# Simulate data
np.random.seed(42)
n_students = 100

# Academic performance
G1 = np.random.randint(5, 20, n_students)
G2 = G1 + np.random.randint(-3, 4, n_students)

# Additional features
study_time = np.random.randint(1, 15, n_students)
chocolates_from_Gabor = np.random.randint(0, 5, n_students)
attendance = np.random.randint(50, 101, n_students)
sleep_hours = np.random.uniform(5, 9, n_students)
internet_usage = np.random.uniform(1, 6, n_students)

# Final grade G3
G3 = (
    0.25 * G1 +
    0.3 * G2 +
    0.2 * study_time +
    0.5 * chocolates_from_Gabor +
    0.1 * attendance / 10 -
    0.2 * internet_usage +
    0.1 * sleep_hours +
    np.random.randn(n_students) * 2
).round()

G3 = np.clip(G3, 0, 20)

# Create DataFrame
data = pd.DataFrame({
    'G1': G1,
    'G2': G2,
    'Study Time': study_time,
    'Chocolates from Gabor': chocolates_from_Gabor,
    'Attendance (%)': attendance,
    'Sleep Hours': sleep_hours,
    'Internet Usage': internet_usage,
    'Final Grade (G3)': G3
})

# Save to Google Drive
from google.colab import drive
drive.mount('/content/drive')

csv_path = '/content/drive/My Drive/simulated_student_data.csv'
data.to_csv(csv_path, index=False)
print(f"File saved to {csv_path}")

import numpy as np
import pandas as pd

# Simulate data
np.random.seed(42)
n_students = 500

# Academic performance
G1 = np.random.randint(5, 20, n_students)
G2 = G1 + np.random.randint(-3, 4, n_students)

# Additional features
study_time = np.random.randint(1, 15, n_students)
chocolates_from_Gabor = np.random.randint(0, 5, n_students)
attendance = np.random.randint(50, 101, n_students)
sleep_hours = np.random.uniform(5, 9, n_students)
internet_usage = np.random.uniform(1, 6, n_students)

# Final grade G3
G3 = (
    0.25 * G1 +
    0.3 * G2 +
    0.2 * study_time +
    0.5 * chocolates_from_Gabor +
    0.1 * attendance / 10 -
    0.2 * internet_usage +
    0.1 * sleep_hours +
    np.random.randn(n_students) * 2
).round()

G3 = np.clip(G3, 0, 20)

# Create DataFrame
data = pd.DataFrame({
    'G1': G1,
    'G2': G2,
    'Study Time': study_time,
    'Chocolates from Gabor': chocolates_from_Gabor,
    'Attendance (%)': attendance,
    'Sleep Hours': sleep_hours,
    'Internet Usage': internet_usage,
    'Final Grade (G3)': G3
})

# Save to Google Drive
from google.colab import drive
drive.mount('/content/drive')

csv_path = '/content/drive/My Drive/simulated_student_data_500.csv'
data.to_csv(csv_path, index=False)
print(f"File saved to {csv_path}")

import numpy as np
import pandas as pd

# Simulate data
np.random.seed(42)
n_students = 1000

# Academic performance
G1 = np.random.randint(5, 20, n_students)
G2 = G1 + np.random.randint(-3, 4, n_students)

# Additional features
study_time = np.random.randint(1, 15, n_students)
chocolates_from_Gabor = np.random.randint(0, 5, n_students)
attendance = np.random.randint(50, 101, n_students)
sleep_hours = np.random.uniform(5, 9, n_students)
internet_usage = np.random.uniform(1, 6, n_students)

# Final grade G3
G3 = (
    0.25 * G1 +
    0.3 * G2 +
    0.2 * study_time +
    0.5 * chocolates_from_Gabor +
    0.1 * attendance / 10 -
    0.2 * internet_usage +
    0.1 * sleep_hours +
    np.random.randn(n_students) * 2
).round()

G3 = np.clip(G3, 0, 20)

# Create DataFrame
data = pd.DataFrame({
    'G1': G1,
    'G2': G2,
    'Study Time': study_time,
    'Chocolates from Gabor': chocolates_from_Gabor,
    'Attendance (%)': attendance,
    'Sleep Hours': sleep_hours,
    'Internet Usage': internet_usage,
    'Final Grade (G3)': G3
})

# Save to Google Drive
from google.colab import drive
drive.mount('/content/drive')

csv_path = '/content/drive/My Drive/simulated_student_data_1000.csv'
data.to_csv(csv_path, index=False)
print(f"File saved to {csv_path}")
